apiVersion: apps/v1
kind: Deployment
metadata:
  name: KubernetesSample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KubernetesSample
  template:
    metadata:
      labels:
        app: KubernetesSample
    spec:
      containers:
      - name: kubernetessample
        image: kubernetes777.azurecr.io/kubernetes777repos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kunal1sn

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetessample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: KubernetesSample